#!/bin/sh
dryrun=
verbose=
while [ $# -gt 0 ]; do
    case "$1" in
        -n)
            dryrun=y
            ;;
        -v)
            verbose=y
            ;;
        *)
            break
    esac
    shift
done
for f in "$@" ; do
  case "$f" in
    *.py)
      [ -n "$verbose" ] && echo "deleting $f"
      [ -z "$dryrun" ] && rm "$f"
      ;;
    *)
      [ -n "$verbose" ] && echo "not deleting $f"            
  esac
done
